# Depends on a solution from: https://github.com/oven-sh/bun/issues/5707

name: Node

on:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: node src/index.js --help
      - run: node src/index.js --version
      - run: node src/index.js < .github/workflows/node.yml
