# Depends on a solution from: https://github.com/oven-sh/bun/issues/5707

name: Node

on:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: node dist/index.js --help
      - run: node dist/index.js --version
      - run: node dist/index.js .github/workflows/node.yml
      - run: node dist/index.js -l bash 'export TOKEN=value'
      - run: node dist/index.js -l yml < .github/workflows/node.yml
