name: Preview

on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1
        with:
          bun-version: 1.0.7
      - run: bun install
      - name: make an html file
        run: |
         cat .github/workflows/preview.yml | bun run src/index.ts -l yml \
           --html-wrap --output-file=preview.html
         cat preview.html  | grep '<html>'
         cat preview.html  | grep '<html>'
         cat preview.html  | grep '<code class="hljs">'
         cat preview.html  | grep '<span class="hljs-attr">name:</span>'
      - name: generate CSS output
        run: |
          bun run css > default.css
          grep '.hljs {' default.css
          grep 'background: #F3F3F3;' default.css
          bun run css gradient-light > gradient-light.css
          grep '.hljs {' gradient-light.css
          grep 'background-color: #f9ccff;' gradient-light.css
          bun run list-css | grep xcode
      - name: start a preview server
        run: |
         bun run src/index.ts .github/workflows/preview.yml -p > /tmp/stdout.log 2> /tmp/stderr.log &
      - name: wait for server to start
        run: curl --retry 3 --retry-connrefused http://localhost:3000
      - name: test preview server outputs
        run: |
         set -e
         curl http://localhost:3000 > output.html
         grep '<span class="hljs-attr">name:</span>' output.html
         grep '<style type="text/css">' output.html
         echo "Specifying a custom CSS"
         curl "http://localhost:3000?css=gradient-light" > output2.html
         cmp output.html output2.html && exit 1
         curl --fail "http://localhost:3000?css=neverheardof" && exit 2 || echo "expected to fail"
      - name: Debug server outputs on errors
        if: ${{ failure() }}
        run: |
           echo "____STDOUT____"
           cat /tmp/stdout.log
           echo "____STDERR____"
           cat /tmp/stderr.log
